binop_separator = "Back"
combine_control_expr = false
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
hard_tabs = true
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
max_width = 80
use_field_init_shorthand = true
