[package]
authors = ["Rakshith Ravi <rakshith.ravi@gmx.com>"]
edition = "2018"
name = "express-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version = "1.6.2", features = ["attributes"]}
async-trait = "0.1.36"
hyper = "0.13.6"
serde_json = "1.0.57"
tokio = { version = "0.2.22", features = ["full"] }
regex = "1.3.9"
serde = "1.0.114"
