[package]
authors = ["Rakshith Ravi <rakshith.ravi@gmx.com>"]
edition = "2018"
name = "eve-rs"
version = "0.1.0"
description = "A simple, intuitive, express-like HTTP library"
license = "MIT"
documentation = "https://docs.rs/eve-rs"
homepage = "https://github.com/bytesonus/eve-rs"
repository = "https://github.com/bytesonus/eve-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version = "1.6.2", features = ["attributes"]}
async-trait = "0.1.36"
hyper = { version = "0.13.6", default-features = false }
serde_json = "1.0.57"
tokio = { version = "0.2.22", default-features = false }
regex = "1.3.9"
serde = "1.0.114"
log = "0.4.11"
chrono = "0.4.13"
colored = "2.0.0"
serde_urlencoded = "0.6.1"
flate2 = "1.0.16"
futures = "0.3.5"
